### ISSUE TITLE
How to run the inference and visualization demo based on pretrained model

### ISSUE THREAD

**Issue by SeaOfOcean** [liamw96/pytorch.room.layout#2]

**Comment by liamw96** [comment]
could you please elaborate your problems?

**Comment by alex-kravets** [comment]
I think it will be much convenient if you provide 'info.json' files separately from the zip archives.
Maybe it was the case, I'm not sure :)  But it was my very first idea when I decided to try to run inference on pre-trained model.
BTW, can you please upload those json files? It is quite inconvenient to download at least 1.4G dataset to get single file) Thanks !

**Comment by liamw96** [comment]
@alex-kravets Hi there! Actually for natural images, one can reuse the color statistics. For example, this one is just fine: https://github.com/fyu/drn/blob/master/datasets/cityscapes/info.json

You can also use the pytorch official info.json for ImageNet

**Comment by run-me** [comment]
![Screenshot_2019-08-23_16-30-00](https://user-images.githubusercontent.com/47290702/63624965-ca030180-c5c3-11e9-8c9b-690a82fde909.png)
The model works like a charm, @liamw96 thanks for all your efforts and making this work open source. Working on vis methods will create a pull request when I am done working on it. Thanks again man! cheers!

**Comment by liamw96** [comment]
@run-me  thanks for your encouraging comments!

**Comment by Chris20200910** [comment]
Hi, I hope get results like 
![image](https://user-images.githubusercontent.com/41281748/147524209-c2bef474-b082-4a2f-93a0-483c853881f9.png)
But I only get results like 
![image](https://user-images.githubusercontent.com/41281748/147524101-92476199-8127-415f-9a5d-26d15461535b.png)

So, what should I do?
