### ISSUE TITLE
Would you please share the PIO part code？

### ISSUE THREAD

**Issue by Wap8CN** [liamw96/pytorch.room.layout#6]
I want to get the cordinates of  the predicted corners。It seems the current net only shows the raw picture result. By the way, thanks for your share about the network. It already helped me a lot. Even though you can't share the PIO part, it's okay. 
你好，能看懂中文吗？如果不方便分享pio相关代码的话，可以讲一下实现细节思路嘛，我试试能不能复现一下。万分感谢～

**Comment by Chris20200910** [comment]
@Wap8CN 你好，我也想要PIO相关代码， 不知道你是否方便分享，万分感谢

**Comment by zhangjingxian1998** [comment]
你好，请问你是否复现成功呢
